import {
  FANTRAX_LEAGUE_ID,
  FantraxError,
  type Bridge,
  type FootballSnapshot,
  type RosteredPeriod,
  fetchTeamRosters,
  getFootballSnapshot,
  mapTeamRosters,
  resolveRosters,
} from "@epl/core";
import mapping from "../../../../data/mappings/fantrax.json";

// Where the app supplies the bridge. It has to happen here rather than in core:
// `packages/core/tsconfig.json` includes only `src/**/*.ts`, so core physically
// cannot read `data/mappings/`, and that compiler boundary is what keeps the
// human-audited mapping at the edge where a person can see it.

// The file is ours — generated by `npm run bridge` and audited by hand — but a
// JSON import widens `matchedBy` to `string`, and the compiler cannot see that
// the writer only ever emits the four literals. Asserted once, here, rather than
// loosening `MappedEntry` to accept any string for the sake of an import.
const bridge = mapping as Bridge;

/** Everything a squad view needs, or the reason there isn't one.
 *
 *  Two reasons, and they must never be one. `NO_TEAMS` is what our real league
 *  answers until draft night: an expected state, not a fault, so it is modelled
 *  and returned rather than thrown. Everything else `FantraxError` carries is
 *  Fantrax failing to answer — an HTTP status from the client's transport
 *  backstop, or a mistyped league id answering INVALID_LEAGUE_ID.
 *
 *  Collapsing the two tells sixteen managers with squads that nobody has drafted
 *  yet, because Fantrax blipped for five minutes. That is a confident wrong
 *  statement about the league from the one route whose job is to report it. */
export type LeagueSquads =
  | { period: RosteredPeriod; snapshot: FootballSnapshot }
  | { undrafted: string }
  | { unavailable: string };

export async function getLeagueSquads(): Promise<LeagueSquads> {
  const [snapshot, rosters] = await Promise.all([
    getFootballSnapshot(),
    fetchTeamRosters(FANTRAX_LEAGUE_ID).catch((error: unknown) => {
      if (error instanceof FantraxError) return error;
      throw error;
    }),
  ]);

  // Branching on a specific code, which the adapter deliberately never does
  // (PLATFORM_NOTES). Safe here because it fails toward hedging: an unrecognised
  // code says "Fantrax is not answering", which is a hedged right answer even
  // for a league that genuinely has no teams.
  if (rosters instanceof FantraxError) {
    return rosters.code === "NO_TEAMS"
      ? { undrafted: rosters.code }
      : { unavailable: rosters.code };
  }

  return {
    period: resolveRosters(snapshot, mapTeamRosters(rosters), bridge),
    snapshot,
  };
}
