import {
  FANTRAX_LEAGUE_ID,
  FantraxError,
  type Bridge,
  type FootballSnapshot,
  type RosteredPeriod,
  fetchTeamRosters,
  getFootballSnapshot,
  mapTeamRosters,
  resolveRosters,
} from "@epl/core";
import mapping from "../../../../data/mappings/fantrax.json";

// Where the app supplies the bridge. It has to happen here rather than in core:
// `packages/core/tsconfig.json` includes only `src/**/*.ts`, so core physically
// cannot read `data/mappings/`, and that compiler boundary is what keeps the
// human-audited mapping at the edge where a person can see it.

// The file is ours — generated by `npm run bridge` and audited by hand — but a
// JSON import widens `matchedBy` to `string`, and the compiler cannot see that
// the writer only ever emits the four literals. Asserted once, here, rather than
// loosening `MappedEntry` to accept any string for the sake of an import.
const bridge = mapping as Bridge;

/** Everything a squad view needs, or the reason there isn't one.
 *
 *  `NO_TEAMS` is what our real league answers until 10 Oct. It is an expected
 *  state, not a fault, so it is modelled and returned rather than thrown — a
 *  route that 500s on the correct answer is worse than no route. */
export type LeagueSquads =
  | { period: RosteredPeriod; snapshot: FootballSnapshot }
  | { undrafted: string };

export async function getLeagueSquads(): Promise<LeagueSquads> {
  const [snapshot, rosters] = await Promise.all([
    getFootballSnapshot(),
    fetchTeamRosters(FANTRAX_LEAGUE_ID).catch((error: unknown) => {
      if (error instanceof FantraxError) return error;
      throw error;
    }),
  ]);

  if (rosters instanceof FantraxError) return { undrafted: rosters.code };

  return {
    period: resolveRosters(snapshot, mapTeamRosters(rosters), bridge),
    snapshot,
  };
}
