#!/bin/bash
# PreToolUse guard for Write|Edit|NotebookEdit.
# Two directories hold things a rewrite quietly destroys. Ask, do not deny: both
# have a legitimate hand-edit (the bridge's manual audit rows are the point of
# the bridge), and a hard block would only teach people to work around it.
set -euo pipefail

input=$(cat)
path=$(printf '%s' "$input" | /usr/bin/jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -z "$path" ] && exit 0

root="${CLAUDE_PROJECT_DIR:-$PWD}"
case "$path" in
  "$root"/*) rel="${path#"$root"/}" ;;
  /*) exit 0 ;;                        # outside the project — not ours to police
  *) rel="$path" ;;
esac

ask() {
  /usr/bin/jq -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"ask",permissionDecisionReason:$r}}'
  exit 0
}

case "$rel" in
  data/snapshots/*)
    ask "data/snapshots/ is a point-in-time capture: what Fantrax said on a given day, and the only record of it. Editing one makes the history say something Fantrax never said, and no re-run can restore it. If a capture is wrong, capture again into today's directory and say so." ;;
  data/mappings/*)
    ask "data/mappings/ is generated by 'npm run bridge' and audited by hand — so an edit here is either the audit (fine, and it belongs in the commit message) or a change the next bridge run silently reverts. Which is it?" ;;
esac

exit 0
