// Which shape differences a person has already looked at.
//
// `diffShapes` compares two PAYLOADS. Whether a path the subject does not answer
// actually matters depends on whether any mapper reads it — and that lives in the
// mappers, which a payload differ cannot see. So the judgement is data, audited
// once and checked in, exactly as the identity bridge is: generated by a script,
// read by a person, and never inferred at runtime.
//
// The alternative was tempting and wrong. Widening the "inside an empty
// collection" attribution to cover siblings would green the gate by going blind:
// a standings column genuinely lost on 10 Oct would be swallowed with the rest of
// the subtree. A gate bought green is not a gate.

/** One difference somebody has read and accepted. */
export interface AcknowledgedDifference {
  /** The read it came from — the `method` string `shape-diff` labels each read
   *  with, so the same path under a different read is a different judgement. */
  read: string;
  /** The path exactly as `diffShapes` reports it, type suffix included. */
  path: string;
  /** Why it is acceptable, in a person's words. The field this file exists for:
   *  an entry nobody can explain is an entry nobody should trust. */
  why: string;
}

export interface ShapeResidue {
  /** Missing paths nobody has acknowledged. What the gate reddens on. */
  residue: string[];
  /** Acknowledged paths that no longer differ. Reported so the file can be
   *  pruned rather than quietly growing into a blindfold — the day the real
   *  league answers these, they stop being judgements and become clutter. */
  settled: string[];
}

/** Split one read's missing paths against what has been acknowledged for it. */
export function unacknowledged(
  read: string,
  missing: readonly string[],
  baseline: readonly AcknowledgedDifference[],
): ShapeResidue {
  const acknowledged = baseline.filter((entry) => entry.read === read).map((entry) => entry.path);
  return {
    residue: missing.filter((path) => !acknowledged.includes(path)).sort(),
    settled: acknowledged.filter((path) => !missing.includes(path)).sort(),
  };
}
