import { cookies } from "next/headers";
import { TEAM_COOKIE } from "./config";

// Who is holding the phone.
//
// Sixteen friends, no accounts, no passwords, no database. Each manager gets one
// code from the commissioner and enters it once; the app remembers which team is
// his and takes his side from then on.
//
// Not a dropdown, because this identity is what will authorize *editing* a
// lineup once the write surface exists, and a rival must not be able to become
// you by picking your name off a list. Reading stays wide open — the code buys
// being a team, never access.
//
// Both secrets are read from the environment here rather than from
// `packages/core/src/config.ts`: that module's own doc says anything genuinely
// secret is read at the edges, and this is the edge.

function secret(): string | null {
  // Empty is absent. `??` alone would let `SESSION_SECRET=""` through as a real
  // key, and every code in the league would then verify against an HMAC keyed on
  // nothing — a signature anybody can compute.
  return process.env.SESSION_SECRET || null;
}

/** `teamId → HMAC of that team's code`. Generated by `npm run team-codes`, set in
 *  the deployment, and invisible to git — so it is a numbered step in the
 *  ship-day runbook, exactly like the league id. */
function codeHashes(): Record<string, string> {
  const raw = process.env.TEAM_CODES;
  if (!raw) return {};
  try {
    return JSON.parse(raw) as Record<string, string>;
  } catch {
    // A malformed map means nobody can sign in, which is survivable and visible.
    // Guessing at half-parsed JSON to let *somebody* in is not.
    return {};
  }
}

async function hmac(value: string, key: string): Promise<string> {
  const encoder = new TextEncoder();
  const imported = await crypto.subtle.importKey(
    "raw",
    encoder.encode(key),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign("HMAC", imported, encoder.encode(value));
  return [...new Uint8Array(signature)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Length-independent comparison. Both sides here are hex of a fixed width, so
 *  this is belt and braces rather than the only thing standing up. */
function sameSecret(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let difference = 0;
  for (let i = 0; i < a.length; i++) difference |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return difference === 0;
}

/** The team whose code this is, or null.
 *
 *  Deliberately keyed by the code rather than by a team the manager picks: one
 *  box to fill in, and no list of whose code you might be guessing at. */
export async function teamForCode(code: string): Promise<string | null> {
  const key = secret();
  const trimmed = code.trim().toUpperCase();
  if (key === null || trimmed === "") return null;

  const attempt = await hmac(trimmed, key);
  const match = Object.entries(codeHashes()).find(([, hash]) => sameSecret(hash, attempt));
  return match?.[0] ?? null;
}

/** The signed cookie value for a team. Signed, not stored plain: an unsigned
 *  cookie is the dropdown we just refused, with an extra step. */
export async function sign(teamId: string): Promise<string | null> {
  const key = secret();
  return key === null ? null : `${teamId}.${await hmac(teamId, key)}`;
}

/** Whose team this browser is, or null for a reader who has not signed in.
 *
 *  Verified, then still checked against the league we are actually serving, so a
 *  session from the rehearsal league simply stops working on 10 Oct instead of
 *  quietly highlighting a team that no longer exists. */
export async function myTeamId(teams: readonly { teamId: string }[]): Promise<string | null> {
  // **The cookie is read before anything can return, and that is load-bearing
  // beyond this function.** `cookies()` is what tells Next this render depends on
  // the request; without it these pages are PRERENDERED AT BUILD TIME, and a page
  // built before `FANTRAX_LEAGUE_ID` was set is a page serving the wrong league's
  // squads, standings and scores no matter what the running server is configured
  // for. `leagueCache` puts the id in every cache key to stop exactly that, and it
  // cannot help here, because a static page never reaches the cache at all.
  //
  // It went wrong the moment a `SESSION_SECRET` check returned first: CI has no
  // secret, so six routes built static against the default league while
  // `/league/schedule` — which had no session read — stayed dynamic and correct.
  // Half the app served one league and half the other, and it looked fine.
  const raw = (await cookies()).get(TEAM_COOKIE)?.value;

  const key = secret();
  if (key === null || !raw) return null;

  const at = raw.lastIndexOf(".");
  if (at <= 0) return null;

  const teamId = raw.slice(0, at);
  if (!sameSecret(raw.slice(at + 1), await hmac(teamId, key))) return null;

  return teams.some((team) => team.teamId === teamId) ? teamId : null;
}

