import {
  FANTRAX_LEAGUE_ID,
  FantraxError,
  type Bridge,
  type FootballSnapshot,
  type GameweekKickoff,
  type LeagueInfo,
  type RosterDisplay,
  type RosteredPeriod,
  type RawTeamRosters,
  fetchTeamRosters,
  mapTeamRosters,
  periodToRead,
  resolveRosters,
  rosterDisplay,
} from "@epl/core";
import { leagueInfo, roundOf, type Round } from "./round";
import { now } from "./clock";
import { leagueCache } from "./leagueCache";
import { footballNow, gameweekSnapshot, seasonKickoffs } from "./football";
import { myTeamId } from "./session";
import { shortTeamNames } from "./teamNames";
import { orRefusal, tell } from "./refusals";
import type { Unavailable } from "./refusals";
import mapping from "../../../data/mappings/fantrax.json";
import { notFound, redirect } from "next/navigation";

// Where the app supplies the bridge. It has to happen here rather than in core:
// `packages/core/tsconfig.json` includes only `src/**/*.ts`, so core physically
// cannot read `data/mappings/`, and that compiler boundary is what keeps the
// human-audited mapping at the edge where a person can see it.

// The file is ours — generated by `npm run bridge` and audited by hand — but a
// JSON import widens `matchedBy` to `string`, and the compiler cannot see that
// the writer only ever emits the four literals. Asserted once, here, rather than
// loosening `MappedEntry` to accept any string for the sake of an import.
//
// Exported so that "once" is true: the player page needs the same bridge, and a
// second assertion elsewhere would be a second place to get it wrong.
export const bridge = mapping as Bridge;

/** Everything a squad view needs, or the reason there isn't one.
 *
 *  Two reasons, and they must never be one. `NO_TEAMS` is what our real league
 *  answers until draft night: an expected state, not a fault, so it is modelled
 *  and returned rather than thrown. Everything else `FantraxError` carries is
 *  Fantrax failing to answer — an HTTP status from the client's transport
 *  backstop, or a mistyped league id answering INVALID_LEAGUE_ID.
 *
 *  Collapsing the two tells sixteen managers with squads that nobody has drafted
 *  yet, because Fantrax blipped for five minutes. That is a confident wrong
 *  statement about the league from the one route whose job is to report it. */
export interface ReadableSquads {
  /** The season's kickoffs, carried for the gate. Lineups lock fifteen minutes
   *  before a period's first ball, and on 33 of this season's 38 weeks that ball
   *  is a day after the period opens — so the gate cannot answer from the league
   *  calendar alone, and `teamDisplay` stays synchronous by being handed this
   *  rather than fetching it. */
  kickoffs: GameweekKickoff[];
  period: RosteredPeriod;
  snapshot: FootballSnapshot;
  /** The league-wide answer: what a reader may see of a team that is not his.
   *  One team a known reader is looking at gets `teamDisplay` instead. */
  display: RosterDisplay;
  /** Null when Fantrax would not describe the competition. Costs the lineup
   *  gate its calendar and the planner its rules, both of which then degrade
   *  rather than guess. */
  info: LeagueInfo | null;
  /** The period the round in view is scored in — what every genuinely
   *  per-period read wants. Distinct from `period.period`, which is the period
   *  FANTRAX says this roster is, and which is the only one the gate may judge. */
  roundPeriod: number | null;
}

export type LeagueSquads = ReadableSquads | { undrafted: string } | Unavailable;

/** The squads, or the page each refusal belongs on.
 *
 *  **Extracted at four** — both squad tabs, the match tab and the head-to-head
 *  board each wrote the same two lines. They are not boilerplate: they are a
 *  decision about what the two refusals MEAN, and `squad/[teamId]/team.ts` had
 *  carried the argument for it in prose while four files made it by hand.
 *
 *  `undrafted` is a genuine 404 — there is no such screen yet. `unavailable` is
 *  not: Fantrax being unreachable is a state of OURS, and it belongs on an index
 *  where it is described rather than hidden behind a status code.
 *
 *  **`home` is the argument because it is what varies**, and finding that out is
 *  what stopped this being an extraction of three and a near-miss: the squad
 *  screens send a refusal to `/squad` and the head-to-head board sends it to
 *  `/league/matchups`, because a reader who cannot be shown a pairing belongs
 *  back on the board he came from and not in a list of squads.
 *
 *  Both `notFound()` and `redirect()` return `never`, so this narrows the union
 *  for the caller and no site needs its own guard afterwards. */
/** The squads read's cache key, which a lineup save expires. */
export const SQUADS_KEY = "league-squads";

export function readableOr404(squads: LeagueSquads, home: string): ReadableSquads {
  if ("undrafted" in squads) notFound();
  if ("unavailable" in squads) redirect(home);
  return squads;
}

/** What the cache can hold.
 *
 *  Plain data, on purpose: a cache round trip serialises, so a `FantraxError`
 *  would come back as a lookalike object and `instanceof` would quietly answer
 *  false — turning "Fantrax refused" into "Fantrax returned nothing" at the one
 *  branch that must tell those apart. The refusal is carried as the two fields
 *  the caller actually reads. */
interface CachedLeague {
  rosters: RawTeamRosters | null;
  refusal: { code: string; tell: string } | null;
  info: LeagueInfo | null;
  /** The period the round in view is scored in, or null when the calendar could
   *  not say. Sent to `getTeamRosters` only through `periodToRead`, which is
   *  what decides whether it may be asked for — see the read below. */
  roundPeriod: number | null;
}

/** The three provider reads every squad view shares, cached across requests.
 *
 *  This is what makes the session cookie affordable. Reading a cookie makes a
 *  route dynamic, and dynamic used to mean sixteen phones each asking FPL for a
 *  1.3 MB bootstrap every thirty seconds. Caching the reads rather than the page
 *  keeps the personalisation and drops the load: the league is shared, so it is
 *  fetched once and rendered sixteen ways.
 *
 *  Nothing about *who is asking* may cross into here — no team id, no cookie —
 *  or one manager's view would be served to another. */
const readLeague = leagueCache(SQUADS_KEY,
  async (round: Round | null, currentGameweek: number): Promise<CachedLeague> => {

    // The period the ROUND IN VIEW is scored in. It is what every genuinely
    // per-period read wants — the scores, the pairing, the heading — because the
    // two calendars turn over at different instants and the page must be one
    // week's throughout.
    //
    // It is sent to `getTeamRosters` for a round ahead of Fantrax's own label —
    // the week the squad screens are about — and, behind it, only for one
    // Fantrax has finished with that our own calendar says has locked.
    // `periodToRead` holds both halves of that argument and the evidence.
    const roundPeriod = round?.period ?? (await roundOf(currentGameweek))?.period ?? null;

    const [open, info, kickoffs] = await Promise.all([
      orRefusal(fetchTeamRosters(FANTRAX_LEAGUE_ID)),
      leagueInfo(),
      seasonKickoffs(),
    ]);

    // A second read, for any round that is not the one Fantrax hands over
    // unasked. Its own open label is not knowable without asking, so the
    // unparameterised read has to happen first — which is why this is sequential
    // and why it costs one extra request on every round but the live one.
    const asked =
      open instanceof FantraxError
        ? null
        : periodToRead(
            roundPeriod,
            open.period ?? null,
            info?.rosterPeriods ?? [],
            kickoffs,
            now().toISOString(),
          );
    const rosters =
      asked === null ? open : await orRefusal(fetchTeamRosters(FANTRAX_LEAGUE_ID, asked));

    return rosters instanceof FantraxError
      ? { rosters: null, refusal: { code: rosters.code, tell: tell(rosters) }, info, roundPeriod }
      : { rosters, refusal: null, info, roundPeriod };
  },
  (error) => ({ rosters: null, refusal: { code: error.code, tell: tell(error) }, info: null, roundPeriod: null }),
);

export async function getLeagueSquads(round: Round | null = null): Promise<LeagueSquads> {
  // The season's kickoffs come from their OWN cache rather than from inside
  // `readLeague`: `CachedLeague` crosses the cache boundary, and serialising 380
  // kickoff rows into every `league-squads` entry would duplicate a payload that
  // already has a cache with its own lifetime. This is a hit, not a request.
  //
  // The football snapshot is read OUT here, never inside `readLeague`: a nested `unstable_cache`
  // bypasses its own cache (Next's unstable-cache.js), so inside it refetched FPL's 1.3 MB bootstrap
  // on every league revalidation and froze a live score in the league's entry. `footballNow` for
  // the round FPL points at, the cold cache for any other — the warm one is kept hot by every page.
  const current = await footballNow();
  const [{ rosters, refusal, info, roundPeriod }, snapshot, kickoffs] = await Promise.all([
    readLeague(round, current.gameweek),
    round === null || round.gameweek === current.gameweek ? current : gameweekSnapshot(round.gameweek),
    seasonKickoffs(),
  ]);

  // Branching on a specific code, which the adapter deliberately never does
  // (PLATFORM_NOTES). Safe here because it fails toward hedging: an unrecognised
  // code says "Fantrax is not answering", which is a hedged right answer even
  // for a league that genuinely has no teams.
  if (refusal !== null || rosters === null) {
    const said = refusal ?? { code: "UNKNOWN", tell: "getTeamRosters → no answer" };
    return said.code === "NO_TEAMS" ? { undrafted: said.tell } : { unavailable: said.tell };
  }

  const held = mapTeamRosters(rosters);
  const period = resolveRosters(snapshot, { ...held, teams: shortTeamNames(held.teams) }, bridge);

  return {
    period,
    roundPeriod,
    snapshot,
    info,
    // The clock is read here and passed in, never inside the gate: §5 keeps
    // `visibility.ts` pure so its boundary is testable, and this is the edge
    // where an instant is allowed to come from the machine.
    //
    // `false` and not the reader's own answer, deliberately. This value is
    // computed once for the whole league and read by everything that reports on
    // every team at once — the pending clean sheets on the matchups board, for
    // one. A reader's own answer applied there would show fifteen rivals' XIs
    // through the side door. The one team a known reader is looking at gets its
    // own answer, at the route that knows which team that is.
    kickoffs,
    // Judged on the period the PAYLOAD declares, never on one we chose — which
    // for any round but the live one is the one `periodToRead` asked for, and otherwise is
    // whichever Fantrax considers open. Checking the echo against our own number
    // would be true by construction and protect nothing.
    display: rosterDisplay(
      period.period,
      info?.rosterPeriods ?? [],
      kickoffs,
      now().toISOString(),
      false,
    ),
  };
}

/** What the reader may see of ONE team's roster, which is not what the league
 *  sees of all of them.
 *
 *  Replaces the `?preview=1` escape hatch and the rehearsal-league check that
 *  guarded it. Those existed because the gate withheld the reader's own lineup
 *  along with everybody else's, so the only way to work on the planner was to
 *  turn the gate off somewhere it could do no harm. The rule is narrower now —
 *  your own team, always; every other team, only once its lineups lock — so
 *  there is nothing left to switch off. */
export function teamDisplay(squads: ReadableSquads, yours: boolean): RosterDisplay {
  return rosterDisplay(
    squads.period.period,
    squads.info?.rosterPeriods ?? [],
    squads.kickoffs,
    now().toISOString(),
    yours,
  );
}

/** The reader's own team, or null — for a page that has not already narrowed the
 *  league to something it can read.
 *
 *  Three screens spelled this out for themselves, and one of them had already
 *  named it. The narrowing is the part worth sharing: every one of them had to
 *  remember that a league which is unavailable or undrafted has no teams to
 *  validate a cookie against, and that a reader with no cookie is null rather
 *  than an error.
 *
 *  The read is cached, so this costs a lookup rather than a request. A page that
 *  has already narrowed `squads` itself calls `myTeamId` directly — it is one
 *  line, and wrapping it would be a wrapper that forwards its argument. */
export async function readerTeamId(): Promise<string | null> {
  const squads = await getLeagueSquads();
  return "period" in squads ? myTeamId(squads.period.teams) : null;
}
