import {
  FANTRAX_LEAGUE_ID,
  FantraxError,
  type Bridge,
  type FootballSnapshot,
  type GameweekKickoff,
  type LeagueInfo,
  type RosterDisplay,
  type RosteredPeriod,
  type RawTeamRosters,
  fetchLeagueInfo,
  fetchTeamRosters,
  mapLeagueInfo,
  mapTeamRosters,
  periodGameweeks,
  resolveRosters,
  rosterDisplay,
} from "@epl/core";
import { leagueCache } from "./leagueCache";
import { footballNow, gameweekSnapshot, seasonKickoffs } from "./football";
import { myTeamId } from "./session";
import { orRefusal, tell } from "./refusals";
import type { Unavailable } from "./refusals";
import mapping from "../../../data/mappings/fantrax.json";

// Where the app supplies the bridge. It has to happen here rather than in core:
// `packages/core/tsconfig.json` includes only `src/**/*.ts`, so core physically
// cannot read `data/mappings/`, and that compiler boundary is what keeps the
// human-audited mapping at the edge where a person can see it.

// The file is ours — generated by `npm run bridge` and audited by hand — but a
// JSON import widens `matchedBy` to `string`, and the compiler cannot see that
// the writer only ever emits the four literals. Asserted once, here, rather than
// loosening `MappedEntry` to accept any string for the sake of an import.
//
// Exported so that "once" is true: the player page needs the same bridge, and a
// second assertion elsewhere would be a second place to get it wrong.
export const bridge = mapping as Bridge;

/** Everything a squad view needs, or the reason there isn't one.
 *
 *  Two reasons, and they must never be one. `NO_TEAMS` is what our real league
 *  answers until draft night: an expected state, not a fault, so it is modelled
 *  and returned rather than thrown. Everything else `FantraxError` carries is
 *  Fantrax failing to answer — an HTTP status from the client's transport
 *  backstop, or a mistyped league id answering INVALID_LEAGUE_ID.
 *
 *  Collapsing the two tells sixteen managers with squads that nobody has drafted
 *  yet, because Fantrax blipped for five minutes. That is a confident wrong
 *  statement about the league from the one route whose job is to report it. */
export interface ReadableSquads {
  /** The season's kickoffs, carried for the gate. Lineups lock fifteen minutes
   *  before a period's first ball, and on 33 of this season's 38 weeks that ball
   *  is a day after the period opens — so the gate cannot answer from the league
   *  calendar alone, and `teamDisplay` stays synchronous by being handed this
   *  rather than fetching it. */
  kickoffs: GameweekKickoff[];
  period: RosteredPeriod;
  snapshot: FootballSnapshot;
  /** The league-wide answer: what a reader may see of a team that is not his.
   *  One team a known reader is looking at gets `teamDisplay` instead. */
  display: RosterDisplay;
  /** Null when Fantrax would not describe the competition. Costs the lineup
   *  gate its calendar and the planner its rules, both of which then degrade
   *  rather than guess. */
  info: LeagueInfo | null;
  /** The period the round in view is scored in — what every genuinely
   *  per-period read wants. Distinct from `period.period`, which is the period
   *  FANTRAX says this roster is, and which is the only one the gate may judge. */
  roundPeriod: number | null;
}

export type LeagueSquads = ReadableSquads | { undrafted: string } | Unavailable;

/** What the cache can hold.
 *
 *  Plain data, on purpose: a cache round trip serialises, so a `FantraxError`
 *  would come back as a lookalike object and `instanceof` would quietly answer
 *  false — turning "Fantrax refused" into "Fantrax returned nothing" at the one
 *  branch that must tell those apart. The refusal is carried as the two fields
 *  the caller actually reads. */
interface CachedLeague {
  snapshot: FootballSnapshot;
  rosters: RawTeamRosters | null;
  refusal: { code: string; tell: string } | null;
  info: LeagueInfo | null;
  /** The period the round in view is scored in, or null when the calendar could
   *  not say. Never sent to `getTeamRosters` — see the read below. */
  roundPeriod: number | null;
}

/** The three provider reads every squad view shares, cached across requests.
 *
 *  This is what makes the session cookie affordable. Reading a cookie makes a
 *  route dynamic, and dynamic used to mean sixteen phones each asking FPL for a
 *  1.3 MB bootstrap every thirty seconds. Caching the reads rather than the page
 *  keeps the personalisation and drops the load: the league is shared, so it is
 *  fetched once and rendered sixteen ways.
 *
 *  Nothing about *who is asking* may cross into here — no team id, no cookie —
 *  or one manager's view would be served to another. */
const readLeague = leagueCache("league-squads",
  async (round: Round | null): Promise<CachedLeague> => {
    const current = await footballNow();

    // The period the ROUND IN VIEW is scored in. It is what every genuinely
    // per-period read wants — the scores, the pairing, the heading — because the
    // two calendars turn over at different instants and the page must be one
    // week's throughout.
    //
    // **It is still never sent to `getTeamRosters` — but not for the reason that
    // used to be written here.** That reason was that the parameter is inert:
    // asked for period 1 Fantrax returns today's arrangement relabelled 1, so
    // sending it forges a label rather than fetching history, and the lineup
    // gate reads labels. The premise is false. Probed 28 Aug against a claim
    // made that morning, a past period serves its own stored squad and not
    // today's — `fetchTeamRosters` carries the evidence.
    //
    // What survives is a narrower version of the same hazard. We know a past
    // period's copy stops tracking the live one; we do not know WHEN it stops —
    // at that period's own lock, or later, when Fantrax's editable period moves
    // past it. In gameweek 1 those two instants were three days apart. If it is
    // the later, then for those three days `?period=N` answers with a live,
    // still-editable arrangement under a label whose lock has passed, and the
    // gate would publish precisely what it exists to withhold.
    //
    // Omitted, Fantrax labels the payload with its own open period and the gate
    // judges the arrangement it is actually holding, which stays sound whichever
    // way that lands. The price is that a past round shows today's squad under
    // last week's heading — a wrong answer, not an unsafe one, and the matchup
    // page says so on screen. One roster change made after a period has locked,
    // then that period re-read, is the whole experiment.
    const roundPeriod = round?.period ?? (await roundOf(current.gameweek))?.period ?? null;

    // `footballNow` for the round FPL is pointing at, and only the cold cache
    // for any other. They are the same read of different rounds, but the warm
    // one is kept hot by every other page — the cold one served a 68-minute-old
    // snapshot under a LIVE badge the one afternoon it was reached alone.
    const [snapshot, rosters, info] = await Promise.all([
      round === null || round.gameweek === current.gameweek
        ? current
        : gameweekSnapshot(round.gameweek),
      orRefusal(fetchTeamRosters(FANTRAX_LEAGUE_ID)),
      leagueInfo(),
    ]);

    return rosters instanceof FantraxError
      ? {
          snapshot,
          rosters: null,
          refusal: { code: rosters.code, tell: tell(rosters) },
          info,
          roundPeriod,
        }
      : { snapshot, rosters, refusal: null, info, roundPeriod };
  },
);

/** A round other than the one Fantrax is currently pointing at.
 *
 *  Both halves are needed and they belong to different layers: the gameweek asks
 *  FPL for that round's football, the period asks Fantrax for that week's
 *  lineups. Resolving one from the other is the calendar seam's job and is done
 *  before this is called, not inside it. */
export interface Round {
  gameweek: number;
  period: number;
}

/** Which Fantrax period a gameweek is scored in, or null for one the league's
 *  calendar does not cover.
 *
 *  The calendar seam, cached on its own because it is the cheapest question the
 *  app asks and the one a route has to answer before it can ask anything else:
 *  you cannot request a period's rosters until you know which period a gameweek
 *  is. Read rather than assumed — the two are one-to-one every week this season
 *  and a postponement is the known way they come apart. */
const readCalendar = leagueCache("league-calendar",
  async () => {
    const [info, kickoffs] = await Promise.all([leagueInfo(), seasonKickoffs()]);
    return info === null ? [] : periodGameweeks(info.scoringPeriods, kickoffs);
  },
);

export async function roundOf(gameweek: number): Promise<Round | null> {
  const found = (await readCalendar()).find((period) => period.gameweeks.includes(gameweek));
  return found === undefined ? null : { gameweek, period: found.period };
}

export async function getLeagueSquads(round: Round | null = null): Promise<LeagueSquads> {
  // The season's kickoffs come from their OWN cache rather than from inside
  // `readLeague`: `CachedLeague` crosses the cache boundary, and serialising 380
  // kickoff rows into every `league-squads` entry would duplicate a payload that
  // already has a cache with its own lifetime. This is a hit, not a request.
  const [{ snapshot, rosters, refusal, info, roundPeriod }, kickoffs] = await Promise.all([
    readLeague(round),
    seasonKickoffs(),
  ]);

  // Branching on a specific code, which the adapter deliberately never does
  // (PLATFORM_NOTES). Safe here because it fails toward hedging: an unrecognised
  // code says "Fantrax is not answering", which is a hedged right answer even
  // for a league that genuinely has no teams.
  if (refusal !== null || rosters === null) {
    const said = refusal ?? { code: "UNKNOWN", tell: "getTeamRosters → no answer" };
    return said.code === "NO_TEAMS" ? { undrafted: said.tell } : { unavailable: said.tell };
  }

  const period = resolveRosters(snapshot, mapTeamRosters(rosters), bridge);

  return {
    period,
    roundPeriod,
    snapshot,
    info,
    // The clock is read here and passed in, never inside the gate: §5 keeps
    // `visibility.ts` pure so its boundary is testable, and this is the edge
    // where an instant is allowed to come from the machine.
    //
    // `false` and not the reader's own answer, deliberately. This value is
    // computed once for the whole league and read by everything that reports on
    // every team at once — the pending clean sheets on the matchups board, for
    // one. A reader's own answer applied there would show fifteen rivals' XIs
    // through the side door. The one team a known reader is looking at gets its
    // own answer, at the route that knows which team that is.
    kickoffs,
    // Judged on the period the PAYLOAD declares, never on one we chose. There is
    // no longer anything to check it against, because nothing is asked — and the
    // guard that used to do the checking compared our number with our own echo,
    // which was true by construction and protected nothing.
    display: rosterDisplay(
      period.period,
      info?.rosterPeriods ?? [],
      kickoffs,
      new Date().toISOString(),
      false,
    ),
  };
}

/** The competition's own description of itself, or none.
 *
 *  A separate read from the rosters and deliberately failure-tolerant: if
 *  Fantrax will not describe the competition we end up with no calendar, and no
 *  calendar means squad-only. Losing the lineup view because a second request
 *  failed is the correct trade — the alternative is showing an XI we cannot
 *  prove is allowed to be shown.
 *
 *  Cached on its own rather than only inside `readLeague`, because three cached
 *  readers want it: the head-to-head route resolves a gameweek to a period
 *  before it can ask for that period's rosters, so an uncached one made two
 *  `getLeagueInfo` requests per window to answer one page — and the table needs
 *  the league's own playoff settings to know where its cut falls. */
export const leagueInfo = leagueCache("league-info",
  async (): Promise<LeagueInfo | null> => {
    const raw = await orRefusal(fetchLeagueInfo(FANTRAX_LEAGUE_ID));
    return raw instanceof FantraxError ? null : mapLeagueInfo(raw);
  },
);

/** What the reader may see of ONE team's roster, which is not what the league
 *  sees of all of them.
 *
 *  Replaces the `?preview=1` escape hatch and the rehearsal-league check that
 *  guarded it. Those existed because the gate withheld the reader's own lineup
 *  along with everybody else's, so the only way to work on the planner was to
 *  turn the gate off somewhere it could do no harm. The rule is narrower now —
 *  your own team, always; every other team, only once its lineups lock — so
 *  there is nothing left to switch off. */
export function teamDisplay(squads: ReadableSquads, yours: boolean): RosterDisplay {
  return rosterDisplay(
    squads.period.period,
    squads.info?.rosterPeriods ?? [],
    squads.kickoffs,
    new Date().toISOString(),
    yours,
  );
}

/** The reader's own team, or null — for a page that has not already narrowed the
 *  league to something it can read.
 *
 *  Three screens spelled this out for themselves, and one of them had already
 *  named it. The narrowing is the part worth sharing: every one of them had to
 *  remember that a league which is unavailable or undrafted has no teams to
 *  validate a cookie against, and that a reader with no cookie is null rather
 *  than an error.
 *
 *  The read is cached, so this costs a lookup rather than a request. A page that
 *  has already narrowed `squads` itself calls `myTeamId` directly — it is one
 *  line, and wrapping it would be a wrapper that forwards its argument. */
export async function readerTeamId(): Promise<string | null> {
  const squads = await getLeagueSquads();
  return "period" in squads ? myTeamId(squads.period.teams) : null;
}
