import { unstable_cache } from "next/cache";
import {
  FANTRAX_LEAGUE_ID,
  FANTRAX_LEAGUES,
  PAGE_REVALIDATE,
  FantraxError,
  type Bridge,
  type FootballSnapshot,
  type LeagueInfo,
  type RosterDisplay,
  type RosteredPeriod,
  type RawTeamRosters,
  fetchLeagueInfo,
  fetchTeamRosters,
  mapLeagueInfo,
  mapTeamRosters,
  resolveRosters,
  rosterDisplay,
} from "@epl/core";
import { footballNow } from "../football";
import { orRefusal, tell } from "../refusals";
import type { Unavailable } from "../refusals";
import mapping from "../../../../data/mappings/fantrax.json";

// Where the app supplies the bridge. It has to happen here rather than in core:
// `packages/core/tsconfig.json` includes only `src/**/*.ts`, so core physically
// cannot read `data/mappings/`, and that compiler boundary is what keeps the
// human-audited mapping at the edge where a person can see it.

// The file is ours — generated by `npm run bridge` and audited by hand — but a
// JSON import widens `matchedBy` to `string`, and the compiler cannot see that
// the writer only ever emits the four literals. Asserted once, here, rather than
// loosening `MappedEntry` to accept any string for the sake of an import.
//
// Exported so that "once" is true: the player page needs the same bridge, and a
// second assertion elsewhere would be a second place to get it wrong.
export const bridge = mapping as Bridge;

/** Everything a squad view needs, or the reason there isn't one.
 *
 *  Two reasons, and they must never be one. `NO_TEAMS` is what our real league
 *  answers until draft night: an expected state, not a fault, so it is modelled
 *  and returned rather than thrown. Everything else `FantraxError` carries is
 *  Fantrax failing to answer — an HTTP status from the client's transport
 *  backstop, or a mistyped league id answering INVALID_LEAGUE_ID.
 *
 *  Collapsing the two tells sixteen managers with squads that nobody has drafted
 *  yet, because Fantrax blipped for five minutes. That is a confident wrong
 *  statement about the league from the one route whose job is to report it. */
export type LeagueSquads =
  | {
      period: RosteredPeriod;
      snapshot: FootballSnapshot;
      display: RosterDisplay;
      /** Null when Fantrax would not describe the competition. Costs the lineup
       *  gate its calendar and the planner its rules, both of which then degrade
       *  rather than guess. */
      info: LeagueInfo | null;
    }
  | { undrafted: string }
  | Unavailable;

/** What the cache can hold.
 *
 *  Plain data, on purpose: a cache round trip serialises, so a `FantraxError`
 *  would come back as a lookalike object and `instanceof` would quietly answer
 *  false — turning "Fantrax refused" into "Fantrax returned nothing" at the one
 *  branch that must tell those apart. The refusal is carried as the two fields
 *  the caller actually reads. */
interface CachedLeague {
  snapshot: FootballSnapshot;
  rosters: RawTeamRosters | null;
  refusal: { code: string; tell: string } | null;
  info: LeagueInfo | null;
}

/** The three provider reads every squad view shares, cached across requests.
 *
 *  This is what makes the session cookie affordable. Reading a cookie makes a
 *  route dynamic, and dynamic used to mean sixteen phones each asking FPL for a
 *  1.3 MB bootstrap every thirty seconds. Caching the reads rather than the page
 *  keeps the personalisation and drops the load: the league is shared, so it is
 *  fetched once and rendered sixteen ways.
 *
 *  Nothing about *who is asking* may cross into here — no team id, no cookie —
 *  or one manager's view would be served to another. */
const readLeague = unstable_cache(
  async (): Promise<CachedLeague> => {
    const [snapshot, rosters, info] = await Promise.all([
      footballNow(),
      orRefusal(fetchTeamRosters(FANTRAX_LEAGUE_ID)),
      leagueInfo(),
    ]);

    return rosters instanceof FantraxError
      ? { snapshot, rosters: null, refusal: { code: rosters.code, tell: tell(rosters) }, info }
      : { snapshot, rosters, refusal: null, info };
  },
  ["league-squads", FANTRAX_LEAGUE_ID],
  { revalidate: PAGE_REVALIDATE },
);

export async function getLeagueSquads(): Promise<LeagueSquads> {
  const { snapshot, rosters, refusal, info } = await readLeague();

  // Branching on a specific code, which the adapter deliberately never does
  // (PLATFORM_NOTES). Safe here because it fails toward hedging: an unrecognised
  // code says "Fantrax is not answering", which is a hedged right answer even
  // for a league that genuinely has no teams.
  if (refusal !== null || rosters === null) {
    const said = refusal ?? { code: "UNKNOWN", tell: "getTeamRosters → no answer" };
    return said.code === "NO_TEAMS" ? { undrafted: said.tell } : { unavailable: said.tell };
  }

  const period = resolveRosters(snapshot, mapTeamRosters(rosters), bridge);

  return {
    period,
    snapshot,
    info,
    // The clock is read here and passed in, never inside the gate: §5 keeps
    // `visibility.ts` pure so its boundary is testable, and this is the edge
    // where an instant is allowed to come from the machine.
    display: rosterDisplay(period.period, info?.rosterPeriods ?? [], new Date().toISOString()),
  };
}

/** The competition's own description of itself, or none.
 *
 *  A separate read from the rosters and deliberately failure-tolerant: if
 *  Fantrax will not describe the competition we end up with no calendar, and no
 *  calendar means squad-only. Losing the lineup view because a second request
 *  failed is the correct trade — the alternative is showing an XI we cannot
 *  prove is allowed to be shown. */
async function leagueInfo(): Promise<LeagueInfo | null> {
  const raw = await orRefusal(fetchLeagueInfo(FANTRAX_LEAGUE_ID));
  return raw instanceof FantraxError ? null : mapLeagueInfo(raw);
}

/** Whether this build may show a lineup the gate would otherwise withhold.
 *
 *  Never for the real league, and the check is which league we serve rather than
 *  an environment variable. An env flag would work until the day someone set it
 *  on the deployment, and leaking sixteen managers' lineups before a deadline is
 *  the one mistake in this app that cannot be taken back. The rehearsal league's
 *  four teams belong to nobody, so there is nothing there to leak.
 *
 *  It is opt-in per request (`?preview=1`) rather than always-on, so the honest
 *  gate stays the default everywhere and remains the thing being tested. */
export function mayPreviewLineups(): boolean {
  const real = FANTRAX_LEAGUES.find((league) => league.key === "real");
  // Fails closed. If the real league cannot be identified — a renamed key, a
  // reordered list — the answer is no, because the failure mode of the other
  // direction is publishing sixteen managers' lineups before a deadline.
  if (!real) return false;
  return FANTRAX_LEAGUE_ID !== real.leagueId;
}
